### ISSUE TITLE
Specific Bulk request.

### ISSUE THREAD

**Issue by dellek** [usb-tools/USBProxy-legacy#77]
Hello,
I'm working on usbproxy software for a university internship and I would like to know if it is possible to perform a bulk read / write request on a specific sector of a master boot record on a usb device,and if it is how to do it.
Thanks in advance.

**Comment by dominicgs** [comment]
Hi,

What are you trying to achieve?

I ask because to perform a bulk read or write on a specific sector you should be able to do it from your OS or, if that abstracts away some detail, using libUSB / pyUSB.  USBProxy doesn't really help you here.

**Comment by dellek** [comment]
The goal is to create a filter, using and/or extending already those present on usbproxy, which passes only certain packets, a sort of firewall for usb (aka BadUSB).
I'm learning these days to use the libusb library, I've already 'done some bulk write and read, but' obviously I can not send a read on a primary partition of a usb.

**Comment by straithe** [comment]
Hi, would you still like assistance with this issue?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
